### ISSUE TITLE
Indexing part of the initialization!

### ISSUE THREAD

**Issue by amin-saffari** [kaizhang/Taiji#1]
Hi Kai,

I was reading your code to have a better understanding of it! I was wondering to ask if
[starMkIndex](https://github.com/kaizhang/Taiji/blob/master/taiji/app/Component/Initialization.hs#L72), [bwaMkIndex](https://github.com/kaizhang/Taiji/blob/master/taiji/app/Component/Initialization.hs#L64), [rsemMkIndex](https://github.com/kaizhang/Taiji/blob/master/taiji/app/Component/Initialization.hs#L81) functions are defined? If so where can I find their type signature?
Thanks in advance and Cheers,
Amin

**Comment by kaizhang** [comment]
These functions are imported from  `Bio.Pipeline.NGS` which is defined [here](https://github.com/kaizhang/bio-pipelines). Several additional packages were used in this project, including https://github.com/kaizhang/bioinformatics-toolkit, https://github.com/kaizhang/bio-experiments, and the workflow management backend https://github.com/kaizhang/SciFlow.

**Comment by amin-saffari** [comment]
Thanks!
