### ISSUE TITLE
Link_TF_gene: Failed!

### ISSUE THREAD

**Issue by gkumar09** [kaizhang/Taiji#8]
Hi there,

I am running taiji and its giving me the following error. First I thought this could be due to haskell or cabal installation, but even after their updates I am getting it:

[LOG][01-11 20:47] ATAC_callpeaks: Finished.
[LOG][01-11 20:47] Find_TF_sites_prepare: running...
[LOG][01-11 20:47] Find_TF_sites_prepare: Finished.
[LOG][01-11 20:47] Find_TF_sites: running...
[LOG][01-12 02:21] Find_TF_sites: Finished.
[LOG][01-12 02:21] Find_TF_sites_merge: running...
[LOG][01-12 02:21] Find_TF_sites_merge: Finished.
[LOG][01-12 02:21] Link_TF_gene_prepare: running...
[LOG][01-12 02:21] Link_TF_gene_prepare: Finished.
[LOG][01-12 02:21] Output_TF_sites: running...
[LOG][01-12 02:24] Output_TF_sites: Finished.
[LOG][01-12 02:24] Link_TF_gene: running...
[WARN][01-12 02:25] Link_TF_gene: Failed!
[ERROR][01-12 02:25] "Link_TF_gene" failed. The error was: src/Bio/GO/GREAT.hs:39:5-82: Irrefutable pattern failed for pattern (rs, Just (r, a))

**Comment by kaizhang** [comment]
Sry for the late response! Have you found the solution? Have you looked at #2?
